name: Weather Text Alerts

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:


jobs:
  run-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run weather script
        env:
          OPENWEATHER_KEY: ${{ secrets.OPENWEATHER_KEY }}
          LAT: ${{ secrets.LAT }}
          LON: ${{ secrets.LON }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_1: ${{ secrets.TELEGRAM_CHAT_1 }}
          TELEGRAM_CHAT_2: ${{ secrets.TELEGRAM_CHAT_2 }}

         
        run: python weather.py
